FROM registry.access.redhat.com/ubi8/ubi 
RUN yum -y install lksctp-tools-devel gcc lksctp-tools-devel kernel-modules-extra && yum clean all -y
RUN gcc sctp.c -o /usr/bin/local/sctpclient -lsctp
CMD ["/usr/bin/local/sctpclient"]