kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "sctp-sample-build"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "ImageChange"
  source:
    git:
      uri: "https://github.com/fedepaol/sctp_setup"
      ref: "master"
      contextDir: "samplebuild/src"
    secrets:
      - secret:
          name: etc-pki-entitlement
        destinationDir: etc-pki-entitlement
  strategy:
    dockerStrategy:
      dockerfilePath: "samplebuild/src/Dockerfile.sctp"
  output:
    to:
      kind: "ImageStreamTag"
      name: "sctp-sample:latest"
